print("Hello Welcome to Indian OpenSource Community")
print("Hello Welcome to Indian OpenSource Community")
print("Hello Welcome to Indian OpenSource Community")
print("Hello Welcome to Indian OpenSource Community")
print("Hello Welcome to Indian OpenSource Community")
print("Hello Welcome to Indian OpenSource Community")
print("Hello Welcome to Indian OpenSource Community")
